version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - Johann-S
  - XhmikosR
  labels:
  - dependencies
  - v5
  versioning-strategy: increase
  ignore:
  - dependency-name: karma-browserstack-launcher
    versions:
    - 1.5.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: hugo-bin
    versions:
    - 0.68.0
    - 0.69.0
    - 0.70.0
  - dependency-name: lockfile-lint
    versions:
    - 4.3.7
    - 4.6.1
  - dependency-name: lodash
    versions:
    - 4.17.20
